```python
import subprocess

class ShellException(Exception):
    def __init__(self, code, stdout='', stderr=''):
        self.code = code
        self.stdout = stdout
        self.stderr = stderr

    def __str__(self):
        return 'exit code %d - %s' % (self.code, self.stderr)

def run_command(command):
    # Run the command and wait for it to complete
    proc = subprocess.Popen(command.split(' '), stdout=subprocess.PIPE,
                            stderr=subprocess.PIPE)
    proc.wait()

    stdout, stderr = proc.communicate()

    if proc.returncode > 0:
        raise ShellException(proc.returncode, stdout, stderr)

    return stdout

run_command('/opt/1.log')

```
result
```
python_test# python run_shell_test.py 
Traceback (most recent call last):
  File "run_shell_test.py", line 25, in <module>
    run_command('/opt/1.log')
  File "run_shell_test.py", line 15, in run_command
    stderr=subprocess.PIPE)
  File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

```